import 'package:equatable/equatable.dart';

import '../../../../core/constants/constants.dart';
import '../parsers/community_user_join.dart';

class CommentModel extends Equatable {
  final String id;
  final String postId;
  final String userId;
  final String? parentId;
  final String content;
  final DateTime createdAt;
  final int likesCount;
  final int repliesCount;
  final bool isLikedByMe;

  // Joined from user_data (same source as [UserDataModel] / [UserDataService])
  final String userName;
  final String userAvatar;

  const CommentModel({
    required this.id,
    required this.postId,
    required this.userId,
    this.parentId,
    required this.content,
    required this.createdAt,
    this.likesCount = 0,
    this.repliesCount = 0,
    this.isLikedByMe = false,
    required this.userName,
    required this.userAvatar,
  });

  factory CommentModel.fromJson(Map<String, dynamic> json, {bool isLikedByMe = false}) {
    final joined = communityUserJoinRow(json);

    return CommentModel(
      id: json['id'] as String,
      postId: json['post_id'] as String,
      userId: json['user_id'] as String,
      parentId: json['parent_id'] as String?,
      content: json['content'] as String,
      createdAt: DateTime.parse(json['created_at'] as String).toLocal(),
      likesCount: (json['likes_count'] as num?)?.toInt() ?? 0,
      repliesCount: (json['replies_count'] as num?)?.toInt() ?? 0,
      isLikedByMe: isLikedByMe,
      userName: (joined?['name'] ?? 'Unknown User').toString(),
      userAvatar: (joined?['picture'] ?? kImagePlaceHolder).toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // id is generated by DB usually
      if (id.isNotEmpty) 'id': id,
      'post_id': postId,
      'user_id': userId,
      'parent_id': parentId,
      'content': content,
      // created_at is handled by DB defaults, but we can pass it
      'likes_count': likesCount,
      'replies_count': repliesCount,
    };
  }

  CommentModel copyWith({
    String? id,
    String? postId,
    String? userId,
    String? parentId,
    String? content,
    DateTime? createdAt,
    int? likesCount,
    int? repliesCount,
    bool? isLikedByMe,
    String? userName,
    String? userAvatar,
  }) {
    return CommentModel(
      id: id ?? this.id,
      postId: postId ?? this.postId,
      userId: userId ?? this.userId,
      parentId: parentId ?? this.parentId,
      content: content ?? this.content,
      createdAt: createdAt ?? this.createdAt,
      likesCount: likesCount ?? this.likesCount,
      repliesCount: repliesCount ?? this.repliesCount,
      isLikedByMe: isLikedByMe ?? this.isLikedByMe,
      userName: userName ?? this.userName,
      userAvatar: userAvatar ?? this.userAvatar,
    );
  }

  @override
  List<Object?> get props => [
        id,
        postId,
        userId,
        parentId,
        content,
        createdAt,
        likesCount,
        repliesCount,
        isLikedByMe,
        userName,
        userAvatar,
      ];
}
